#ifndef __ACTIVITY__DEFINE__H
#define __ACTIVITY__DEFINE__H

enum ActivityType {
  ACTIVITY_TYPE_SALES = 0,
  ACTIVITY_TYPE_KILLMOB,
  ACTIVITY_TYPE_FEEDBACK,
  ACTIVITY_TYPE_ENLIST,
  ACTIVITY_TYPE_QPOINT_PRIZE,
  ACTIVITY_TYPE_MAX,
};

#endif  // __ACTIVITY__DEFINE__H

