#!/bin/bash
find ./ -iname \*.h -exec grep --color -wn -H "$1" \{\} \;
find ./ -iname \*.cc -exec grep --color -wn -H "$1" \{\} \;
find ./ -iname \*.cpp -exec grep --color -wn -H "$1" \{\} \;
find ./ -iname \*.c -exec grep --color -wn -H "$1" \{\} \;
